# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.7/en/old-client.html
#
base: &base
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= Settings.db.default.username %>
  password: <%= Settings.db.default.password %>

default: &default
  <<: *base
  host: <%= Settings.db.default.host %>
  port: <%= Settings.db.default.port %>

development:
  <<: *default
  database: coin_now_server_development

test:
  <<: *default
  database: coin_now_server_test
