db:
  default:
    username: <%= ENV['ARTIE_DATABASE_WRITE_USERNAME'] %>
    password: <%= ENV['ARTIE_DATABASE_WRITE_PASSWORD'] %>
    host: <%= ENV['ARTIE_DATABASE_WRITE_HOST'] %>
    port: 3306
  readonly:
    username: <%= ENV['ARTIE_DATABASE_READ_USERNAME'] %>
    password: <%= ENV['ARTIE_DATABASE_READ_PASSWORD'] %>
    host: <%= ENV['ARTIE_DATABASE_READ_HOST'] %>

client:
  application_token: <%= ENV['ARTIE_APPLICATION_TOKEN'] %>
